-- 1.Retrieve all transactions from the brand 'HP'.
select * from sales where brand='HP';

-- 2.List all unique cities where laptops were sold.
SELECT DISTINCT City FROM sales;

-- 3.Find the total number of units sold across all brands.
select sum(units_sold)as total_number_of_units_sold from sales;

-- 4.Get the names of customers who paid using a 'Credit Card'.
select customer_name from sales where payment_method='Credit Card';

-- 5.Show all transactions that occurred in 'December'.
select * from sales where month='December';

-- 6.Calculate the total revenue generated by each brand.
SELECT 
    brand, SUM(units_sold * price_per_unit) AS total_revenue
FROM
    sales
GROUP BY brand;

-- 7.Find the average rating given by customers for each payment method.
SELECT 
    payment_method, AVG(customer_rating) AS avg_customer_rating
FROM
    sales
GROUP BY payment_method;

-- 8.Identify the top 3 cities with the highest number of transactions.
SELECT 
    City, COUNT(*) AS highest_number_of_transaction
FROM
    sales
GROUP BY City
ORDER BY highest_number_of_transaction DESC
LIMIT 3; 

-- 9.Get the laptop model with the highest total units sold.
SELECT 
    laptop_model, SUM(units_sold) AS highest_total_units_sold
FROM
    sales
GROUP BY laptop_model
ORDER BY highest_total_units_sold DESC
LIMIT 1;

-- 10.Find the youngest customer who purchased a 'MacBook Air'.
SELECT 
    *
FROM
    sales
WHERE
    laptop_model = 'MacBook Air'
ORDER BY customer_age
LIMIT 1;

-- 11.Determine the monthly revenue trend for the year 2024.
SELECT 
    month, SUM(units_sold * price_per_unit) AS revenue
FROM sales
WHERE year = 2024
GROUP BY month
ORDER BY CASE
    WHEN month = 'January' THEN 1
    WHEN month = 'February' THEN 2
    WHEN month = 'March' THEN 3
    WHEN month = 'April' THEN 4
    WHEN month = 'May' THEN 5
    WHEN month = 'June' THEN 6
    WHEN month = 'July' THEN 7
    WHEN month = 'August' THEN 8
    WHEN month = 'September' THEN 9
    WHEN month = 'October' THEN 10
    WHEN month = 'November' THEN 11
    WHEN month = 'December' THEN 12
END;

-- 12.List customers who made more than one purchase (based on Customer Name).
SELECT 
    customer_name, COUNT(*)
FROM
    sales
GROUP BY customer_name
HAVING COUNT(*) > 1;

-- 13.Find out which day of the week had the highest average customer rating.
SELECT 
    week_name, AVG(customer_rating) AS average_customer_rating
FROM
    sales
GROUP BY week_name
ORDER BY average_customer_rating DESC
LIMIT 1;

-- 14.Rank brands by their total revenue and show the top 5.
select * from sales;
SELECT 
    brand, SUM(units_sold * price_per_unit) AS total_revenue
FROM
    sales
GROUP BY brand
ORDER BY total_revenue DESC
LIMIT 5;

-- 15.Get the average unit price for each brand in descending order.
select * from sales;
SELECT 
    brand, AVG(price_per_unit) AS average_unit_price
FROM
    sales
GROUP BY brand
ORDER BY average_unit_price DESC;

